FROM python:3.11.14

#working directory of the model
WORKDIR /iris_predictor

#Downloading the requiremnets.txt
COPY requirements.txt .
RUN pip install -r requirements.txt

#copyin the rest of the code
COPY . .

#exposing the application port
EXPOSE 8000

#command to start fastAPI application
CMD [ "uvicorn","API_Model:app","--host","0.0.0.0","--port","8000"]
